<?php

namespace Database\Seeders;

use App\Models\InsuranceCompany;
use Illuminate\Database\Seeder;

/**
 * شركات التأمين المرخصة في المملكة العربية السعودية
 * (مصدر: قائمة تداول / ويكيبيديا - شركات التأمين السعودية)
 */
class InsuranceCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            [
                'name' => 'Tawuniya (Cooperative)',
                'name_ar' => 'الشركة التعاونية للتأمين',
                'email' => 'info@tawuniya.com.sa',
                'phone' => '+966 11 218 9999',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Bupa Arabia',
                'name_ar' => 'شركة بوبا العربية للتأمين التعاوني',
                'email' => 'info@bupa.com.sa',
                'phone' => '+966 11 290 9999',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Al Rajhi Takaful',
                'name_ar' => 'شركة الراجحي للتأمين التعاوني',
                'email' => 'info@alrajhitakaful.com.sa',
                'phone' => '+966 11 211 9000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'MedGulf (Mediterranean & Gulf)',
                'name_ar' => 'شركة المتوسط والخليج للتأمين وإعادة التأمين التعاوني',
                'email' => 'info@medgulf.com.sa',
                'phone' => '+966 11 275 5555',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة المطالبات',
                'is_active' => true,
            ],
            [
                'name' => 'Walaa Cooperative',
                'name_ar' => 'شركة ولاء للتأمين التعاوني',
                'email' => 'info@walaa.com',
                'phone' => '+966 11 299 6666',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Wataniya (National)',
                'name_ar' => 'الشركة الوطنية للتأمين',
                'email' => 'info@wataniya.com.sa',
                'phone' => '+966 11 218 7000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Arabian Shield',
                'name_ar' => 'شركة الدرع العربي للتأمين التعاوني',
                'email' => 'info@arabianshield.com.sa',
                'phone' => '+966 11 477 7444',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Gulf General Cooperative',
                'name_ar' => 'الشركة الخليجية العامة للتأمين التعاوني',
                'email' => 'info@gulfgeneral.com.sa',
                'phone' => '+966 11 218 8888',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Malath Cooperative',
                'name_ar' => 'شركة ملاذ للتأمين التعاوني',
                'email' => 'info@malath.com.sa',
                'phone' => '+966 11 229 2222',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Al Etihad Cooperative',
                'name_ar' => 'شركة الاتحاد للتأمين التعاوني',
                'email' => 'info@alethiad.com.sa',
                'phone' => '+966 11 273 3333',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة المطالبات',
                'is_active' => true,
            ],
            [
                'name' => 'SAICO (Saudi Arabian)',
                'name_ar' => 'الشركة العربية السعودية للتأمين التعاوني',
                'email' => 'info@saico.com.sa',
                'phone' => '+966 11 218 5555',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الطبي',
                'is_active' => true,
            ],
            [
                'name' => 'ACIG (United Group)',
                'name_ar' => 'المجموعة المتحدة للتأمين التعاوني',
                'email' => 'info@acig.com.sa',
                'phone' => '+966 11 218 4000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Arabia Insurance Cooperative',
                'name_ar' => 'شركة التأمين العربية التعاونية',
                'email' => 'info@arabia-ins.com.sa',
                'phone' => '+966 11 273 2222',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Aljazira Takaful',
                'name_ar' => 'شركة الجزيرة تكافل تعاوني',
                'email' => 'info@aljaziratakaful.com.sa',
                'phone' => '+966 11 299 5555',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Salama Cooperative',
                'name_ar' => 'شركة سلامة للتأمين التعاوني',
                'email' => 'info@salama.com.sa',
                'phone' => '+966 11 293 3333',
                'address' => 'الدمام، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الطبي',
                'is_active' => true,
            ],
            [
                'name' => 'Allianz Saudi Fransi',
                'name_ar' => 'شركة أليانز السعودي الفرنسي للتأمين التعاوني',
                'email' => 'info@allianz.com.sa',
                'phone' => '+966 11 274 4444',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Saudi Indian Cooperative (Wafa)',
                'name_ar' => 'الشركة السعودية الهندية للتأمين التعاوني',
                'email' => 'info@wafa.com.sa',
                'phone' => '+966 11 299 8888',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Saudi Re (Reinsurance)',
                'name_ar' => 'الشركة السعودية لإعادة التأمين التعاوني',
                'email' => 'info@saudire.com.sa',
                'phone' => '+966 11 218 3000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة إعادة التأمين',
                'is_active' => true,
            ],
            [
                'name' => 'Alalamiya (Global)',
                'name_ar' => 'الشركة العالمية للتأمين التعاوني',
                'email' => 'info@alalamiya.com.sa',
                'phone' => '+966 11 218 2000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Al Mutahida Cooperative',
                'name_ar' => 'الشركة المتحدة للتأمين التعاوني',
                'email' => 'info@almutahida.com.sa',
                'phone' => '+966 11 273 4444',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة المطالبات',
                'is_active' => true,
            ],
            [
                'name' => 'AXA Cooperative',
                'name_ar' => 'شركة أكسا للتأمين التعاوني',
                'email' => 'info@axa.com.sa',
                'phone' => '+966 11 218 6000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Amana Cooperative',
                'name_ar' => 'شركة أمانة للتأمين التعاوني',
                'email' => 'info@amana.com.sa',
                'phone' => '+966 11 218 1000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Gulf Union (Ittihad Al Khaleej)',
                'name_ar' => 'شركة اتحاد الخليج للتأمين التعاوني',
                'email' => 'info@guic.com.sa',
                'phone' => '+966 11 299 7777',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Al Ahli Takaful',
                'name_ar' => 'شركة الأهلي للتكافل',
                'email' => 'info@ahli-takaful.com.sa',
                'phone' => '+966 11 218 5000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الصحي',
                'is_active' => true,
            ],
            [
                'name' => 'Enmaa Tokyo Marine',
                'name_ar' => 'شركة الإنماء طوكيو مارين',
                'email' => 'info@enmaa-tm.com.sa',
                'phone' => '+966 11 218 0000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة المطالبات',
                'is_active' => true,
            ],
            [
                'name' => 'Sagr Cooperative',
                'name_ar' => 'شركة الصقر للتأمين التعاوني',
                'email' => 'info@sagr.com.sa',
                'phone' => '+966 11 273 5555',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'الموافقات الطبية',
                'is_active' => true,
            ],
            [
                'name' => 'Buruj Cooperative',
                'name_ar' => 'شركة بروج للتأمين التعاوني',
                'email' => 'info@buruj.com.sa',
                'phone' => '+966 11 218 8000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين الطبي',
                'is_active' => true,
            ],
            [
                'name' => 'Chubb Arabia',
                'name_ar' => 'شركة تشب العربية للتأمين التعاوني',
                'email' => 'info@chubb.com.sa',
                'phone' => '+966 11 299 4444',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'إدارة الموافقات',
                'is_active' => true,
            ],
            [
                'name' => 'Solidarity Saudi Takaful',
                'name_ar' => 'شركة سوليدرتي السعودية للتكافل',
                'email' => 'info@solidarity.com.sa',
                'phone' => '+966 11 299 3333',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'قسم التأمين',
                'is_active' => false, // اندمجت مع الجزيرة تكافل
            ],
            [
                'name' => 'Saudi Enaya Cooperative',
                'name_ar' => 'شركة عناية السعودية للتأمين التعاوني',
                'email' => 'info@enaya.com.sa',
                'phone' => '+966 11 218 9000',
                'address' => 'الرياض، المملكة العربية السعودية',
                'contact_person' => 'الموافقات الطبية',
                'is_active' => false, // اندمجت مع أمانة
            ],
        ];

        foreach ($companies as $company) {
            InsuranceCompany::updateOrCreate(
                ['email' => $company['email']],
                $company
            );
        }
    }
}
